[package]
name = "executor_v2"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
executor_v2 = "0x2"

[dependencies]
layerzero_common = { local = "../../layerzero-common" }
executor_auth = { local = "../executor-auth" }
